name: dev pipeline

on:
  push:
    branches:
      - dev

env:
  ## Sets Deployment API key credentials as environment variabless
  ASTRO_API_TOKEN: ${{ secrets.ASTRONOMER_API_TOKEN_DEV }}

jobs:
 lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black  # Install flake8 for linting and black for formatting
        pip install -r requirements.txt  # Adjust if your dependencies are listed elsewhere

    - name: Run flake8
      run: |
        flake8 dags tests  # Adjust the paths to your source and test directories

    - name: Run black
      run: |
        black --check dags tests  # Adjust the paths to your source and test directories

  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.9.0
      with:
        deployment-id: cm640qzom14ot01khlwso1aja
        pytest: true
        pytest-file: tests/dags/test_dag_example.py