name: prod pipeline

on:
  push:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variabless
  ASTRO_API_TOKEN: ${{ secrets.ASTRONOMER_API_TOKEN_PROD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.9.0
      with:
        deployment-id: cm6419u5p144y01ncidpkj06k